/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BOffcanvas: typeof import('bootstrap-vue-next')['BOffcanvas']
    ContentLoader: typeof import('./src/components/global/ContentLoader.vue')['default']
    HorizontalMenu: typeof import('./src/components/nav/HorizontalMenu.vue')['default']
    LogoHorizontal: typeof import('./src/components/global/LogoHorizontal.vue')['default']
    LogoStacked: typeof import('./src/components/global/LogoStacked.vue')['default']
    PostFeed: typeof import('./src/components/nav/PostFeed.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SinglePostContent: typeof import('./src/components/singlepost/SinglePostContent.vue')['default']
    SinglePostHeader: typeof import('./src/components/singlepost/SinglePostHeader.vue')['default']
    SiteNav: typeof import('./src/components/nav/SiteNav.vue')['default']
  }
}
